import { and, eq, gt, or } from "drizzle-orm";
import { getDb } from "@/db";
import { adminSessions, staffMembers } from "@/db/schema";

const COOKIE = "sai_admin_session";
const SESSION_DAYS = 7;
const PBKDF2_ITERATIONS = 210_000;
export type StaffMember = typeof staffMembers.$inferSelect;
export type AdminActor = { id:string; name:string; identifier:string; loginId:string; role:"owner"|"manager"; requiresPasswordSetup:boolean };

function identity(request:Request){const userId=request.headers.get("oai-authenticated-user-id")?.trim()||"";const email=request.headers.get("oai-authenticated-user-email")?.trim().toLowerCase()||"";const encoded=request.headers.get("oai-authenticated-user-full-name");let name=email||"Owner";if(encoded&&request.headers.get("oai-authenticated-user-full-name-encoding")==="percent-encoded-utf-8")try{name=decodeURIComponent(encoded)}catch{}return{userId,email,name}}
function bytesToHex(bytes:Uint8Array){return Array.from(bytes,b=>b.toString(16).padStart(2,"0")).join("")}
function hexToBytes(hex:string){const out=new Uint8Array(hex.length/2);for(let i=0;i<out.length;i++)out[i]=Number.parseInt(hex.slice(i*2,i*2+2),16);return out}
async function sha256(value:string){return bytesToHex(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value))))}
function readCookie(request:Request,name:string){const entry=(request.headers.get("cookie")||"").split(";").map(v=>v.trim()).find(v=>v.startsWith(`${name}=`));return entry?decodeURIComponent(entry.slice(name.length+1)):""}

export async function getCurrentMember(request:Request,bootstrapOwner=true):Promise<StaffMember|Response>{const current=identity(request);if(!current.userId||!current.email)return Response.json({error:"ChatGPT sign-in required"},{status:401});const db=getDb();let rows=await db.select().from(staffMembers).where(and(eq(staffMembers.active,true),or(eq(staffMembers.identifier,current.userId),eq(staffMembers.identifier,current.email)))).limit(1);if(!rows.length&&bootstrapOwner){const any=await db.select({id:staffMembers.id}).from(staffMembers).limit(1);if(!any.length){const id=crypto.randomUUID();await db.insert(staffMembers).values({id,identifier:current.userId,name:current.name,role:"owner",createdBy:current.userId});rows=await db.select().from(staffMembers).where(eq(staffMembers.id,id)).limit(1)}}return rows[0]||Response.json({error:"You do not have admin access"},{status:403})}

export async function requireAdmin(request:Request,ownerOnly=false,allowSetup=false):Promise<AdminActor|Response>{const member=await getCurrentMember(request);if(member instanceof Response)return member;const actor:AdminActor={id:member.id,name:member.name,identifier:member.identifier,loginId:member.loginId,role:member.role as "owner"|"manager",requiresPasswordSetup:!member.passwordHash};if(ownerOnly&&actor.role!=="owner")return Response.json({error:"Owner access required"},{status:403});if(!member.passwordHash)return allowSetup?actor:Response.json({error:"Set the owner Admin ID and password first",code:"ADMIN_SETUP_REQUIRED"},{status:428});const token=readCookie(request,COOKIE);if(!token)return Response.json({error:"Admin ID and password required",code:"ADMIN_LOGIN_REQUIRED",loginId:member.loginId},{status:401});const tokenHash=await sha256(token);const session=await getDb().select({tokenHash:adminSessions.tokenHash}).from(adminSessions).where(and(eq(adminSessions.tokenHash,tokenHash),eq(adminSessions.staffId,member.id),gt(adminSessions.expiresAt,new Date().toISOString()))).limit(1);if(!session.length)return Response.json({error:"Admin session expired",code:"ADMIN_LOGIN_REQUIRED",loginId:member.loginId},{status:401});return actor}

export async function createPassword(password:string){if(password.length<10||password.length>128)throw new Error("Password must be 10–128 characters");const salt=crypto.getRandomValues(new Uint8Array(16));const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt,iterations:PBKDF2_ITERATIONS},key,256);return{passwordHash:bytesToHex(new Uint8Array(bits)),passwordSalt:bytesToHex(salt)}}
export async function verifyPassword(password:string,member:StaffMember){if(!member.passwordHash||!member.passwordSalt)return false;const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt:hexToBytes(member.passwordSalt),iterations:PBKDF2_ITERATIONS},key,256);const actual=new Uint8Array(bits),expected=hexToBytes(member.passwordHash);if(actual.length!==expected.length)return false;let diff=0;for(let i=0;i<actual.length;i++)diff|=actual[i]^expected[i];return diff===0}
export async function createAdminSession(staffId:string){const token=bytesToHex(crypto.getRandomValues(new Uint8Array(32))),tokenHash=await sha256(token),expiresAt=new Date(Date.now()+SESSION_DAYS*86400000).toISOString();await getDb().insert(adminSessions).values({tokenHash,staffId,expiresAt});return token}
export function sessionCookie(token:string){return `${COOKIE}=${encodeURIComponent(token)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${SESSION_DAYS*86400}`}
export function expiredSessionCookie(){return `${COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`}
export async function revokeCurrentSession(request:Request){const token=readCookie(request,COOKIE);if(token)await getDb().delete(adminSessions).where(eq(adminSessions.tokenHash,await sha256(token)))}
export function isDenied(value:AdminActor|Response):value is Response{return value instanceof Response}
export function cleanText(value:unknown,max=500){return typeof value==="string"?value.trim().slice(0,max):""}
export function cleanLoginId(value:unknown){return cleanText(value,80).toLowerCase().replace(/[^a-z0-9._-]/g,"")}
export function stringList(value:unknown){const items=Array.isArray(value)?value:typeof value==="string"?value.split(/\r?\n|,/g):[];return items.map(item=>cleanText(item,160)).filter(Boolean).slice(0,30)}
